pipeline {
	agent none
	stages {
		stage('build') {
			steps {
				echo 'Build'
			}
		}
		stage('test') {
			steps {
				echo 'Test'
			}
		}
		stage('deploy') {
			steps {
				echo 'Deploy'
			}
		}
	}
}